Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: dev
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-dev-secrets
    PharmaNet_PharmanetProxy__Username: common-dev-secrets
    PharmaNet_PharmanetProxy__Password: common-dev-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-dev-secrets

OpenShift:
  Environment: dev
  ImageProject: d027a8-tools

image:
  stream: medicationstatementservice

resources: 
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 20m
    memory: 512Mi
