Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: vc1
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-vc1-secrets
    PharmaNet_PharmanetProxy__Username: common-vc1-secrets
    PharmaNet_PharmanetProxy__Password: common-vc1-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-vc1-secrets

OpenShift:
  Environment: vc1
  ImageProject: d027a8-tools

image:
  stream: medicationstatementservice

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 1m
    memory: 100Mi
