Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: tr1
  Secrets:
    PharmaNet_PharmanetProxy__Endpoint: common-tr1-secrets
    PharmaNet_PharmanetProxy__Username: common-tr1-secrets
    PharmaNet_PharmanetProxy__Password: common-tr1-secrets
    PharmaNet_PharmanetProxy__ClientCertificatePassword: common-tr1-secrets

OpenShift:
  Environment: tr1
  ImageProject: 2f77cb-tools

image:
  stream: practitionerservice

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 1m
    memory: 100Mi
