kind: Secret
apiVersion: v1
metadata:
  name: {{ include "common.fullname" . }}-secrets
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.Secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
type: Opaque