kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-traffic-from-gateway-to-erx
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              environment: dev
              name: 2f77cb
    - from:
        - namespaceSelector:
            matchLabels:
              environment: test
              name: 2f77cb