name: CI-MedicationStatementService
on:
  push:
    branches:
      - "dev"
    paths: 
      - 'Services/MedicationStatementService/**'
  pull_request:
    branches: 
      - "dev"
    paths: 
      - 'Services/MedicationStatementService/**'
    
  workflow_dispatch:

env:
  APP: MedicationStatementService

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3
          
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        
      - name: Build Claims Service
        run: |
          buildid=$(date +"%Y%m%d").$GITHUB_RUN_ID.$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT
          echo Starting C# Build as $buildid
          dotnet publish $GITHUB_WORKSPACE/Services/$APP/src/$APP.csproj -o $RUNNER_TEMP -c Release
          echo Starting Docker Build
          docker build -f $GITHUB_WORKSPACE/Services/$APP/src/Dockerfile $RUNNER_TEMP

          
      
