on: workflow_dispatch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/Claim'
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/Consent'

