on: workflow_dispatch

jobs:
  scan:
    strategy:
      matrix:
        service: [Claim, Consent, Location, Medication, MedicationDispense, MedicationRequest, MedicationStatement, Patient, Practitioner]
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: ${{ matrix.service }}Service ZAP Scan
        uses: zaproxy/action-baseline@v0.8.2
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/${{ matrix.service }}'
          artifact_name: ${{ matrix.service }}_scan
