on: workflow_dispatch

jobs:
  claim_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: ClaimService ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/Claim'
  
  consent_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: ConsentService ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/Consent'
  
  location_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: LocationService ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/Location'
  
  medication_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: MedicationService ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/Medication'
  
  medicationdispense_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: MedicationDispenceService ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/MedicationDispense'
  
  medicationrequest_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: MedicationRequestService ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/MedicationRequest'
  
  medicationstatement_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: MedicationStatementService ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/MedicationStatement'
  
  patient_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: PatientService ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/Patient'
  
  practitioner_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    steps:
      - name: PractitionerService ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://pnet-vs1.api.gov.bc.ca/api/v1/Practitioner'
