apiVersion: v1
kind: Template
metadata:
  name: ${NAME}-template
  labels:
    app: ${NAME} 
objects:
- apiVersion: v1
  stringData:
    PharmaNet_PharmanetProxy__Endpoint: ${PROXY_ENDPOINT}
    PharmaNet_PharmanetProxy__Username: ${PROXY_USERNAME}
    PharmaNet_PharmanetProxy__Password: ${PROXY_PASSWORD}        
    PharmaNet_PharmanetProxy__ClientCertificatePassword: ${PROXY_CERT_PASSWORD}    
  kind: Secret
  metadata:
    name: ${NAME}-secrets
    labels:
      app: ${NAME} 
  type: Opaque

parameters: 
  - name: NAME
    displayName: Template Name
    description: The name of the template and all related entities (override for multiple deployments in the same namespace)
    value: common
    required: true
  - name: PROXY_ENDPOINT
    displayName: Proxy Endpoint
    description: The certificate password for the Pharmanet Proxy.
    required: true
  - name: PROXY_USERNAME
    displayName: Proxy Username
    description: The certificate password for thePharmanet Proxy.
    required: true
  - name: PROXY_PASSWORD
    displayName: Proxy Password
    description: The certificate password for the Pharmanet Proxy.
    required: true
  - name: PROXY_CERT_PASSWORD
    displayName: Proxy Certificate Password
    description: The certificate password for the Pharmanet Proxy.
    required: true            